- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    personal: "{{ lookup('env', 'HOME') }}/personal"
  tasks:
    - import_tasks: tasks/ssh.yml
    - import_tasks: tasks/git-setup.yml
    - import_tasks: tasks/shell.yml
    - import_tasks: tasks/core-setup.yml
    - import_tasks: tasks/node-setup.yml
    - import_tasks: tasks/dotfiles.yml
