- name: Install Tools with Homebrew
  homebrew: name={{ item }} state=present
  with_items:
    - ack
    - gh
    - gpg
    - nvim
    - tree
  tags:
    - install
    - core-setup
- name: Install Visual Studio Code
  homebrew_cask:
    name: visual-studio-code
    state: present
  tags:
    - install
    - core-setup
- name: Install Raycast
  homebrew_cask:
    name: raycast
    state: present
  tags:
    - install
    - core-setup
